import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/globals.css";
import { Providers } from "@/components/Providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-background min-h-dvh`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
